port-remake: Allow user to edit after viewing diff

diff --git a/Scripts/port-remake b/Scripts/port-remake
--- a/Scripts/port-remake
+++ b/Scripts/port-remake
@@ -64,13 +64,20 @@ if [ 0$regen = 0y ]; then
     $EDITOR pkg-plist.new
     printf "Diff:\n"
     if ! diff -u pkg-plist pkg-plist.new; then
-	printf "Install new plist and test port? y/[n] "
-	read new_plist
-	if [ 0$new_plist = 0y ]; then
-	    mv -f pkg-plist.new pkg-plist
-	else
-	    exit 0
-	fi
+        while [ 0$new_plist != 0i ]; do
+	    printf "(i)nstall new plist (e)dit (a)bort "
+	    read new_plist
+	    if [ 0$new_plist = 0i ]; then
+	        mv -f pkg-plist.new pkg-plist
+            elif [ 0$new_plist = 0e ]; then
+                $EDITOR pkg-plist.new
+                diff -u pkg-plist pkg-plist.new || true
+	    elif [ 0$new_plist = 0a ]; then
+	        exit 0
+            else
+                printf "Invalid selection.\n"
+            fi
+        done
 	make clean
     else
 	printf "No changes to pkg-plist.\n"
