Add man pages for remaining port dev scripts

diff --git a/Scripts/port-diff b/Scripts/port-diff
--- a/Scripts/port-diff
+++ b/Scripts/port-diff
@@ -1,5 +1,41 @@
 #!/bin/sh -e
 
+##########################################################################
+#   Synopsis:
+#       port-diff
+#       
+#   Description:
+#       .B port-diff
+#       runs "diff -ruN" between the committed port and the current working
+#       directory.  The path of the committed port is determined using
+#       CATEGORIES and the directory name of the CWD.
+#       
+#   Arguments:
+#       None
+#       
+#   Returns:
+#       0 on success, non-zero error codes otherwise
+#
+#   See also:
+#       port-check(1), port-create(1), port-mkpatch(1), port-patch-edit(1)
+#       port-remake(1), port-reinstall(1), port-restage(1)
+##########################################################################
+
+usage()
+{
+    printf "Usage: $0\n"
+    exit 64     # sysexits(3) EX_USAGE
+}
+
+
+##########################################################################
+#   Main
+##########################################################################
+
+if [ $# != 0 ]; then
+    usage
+fi
+
 if [ ! -e pkg-descr ] && ! fgrep -q MASTERDIR Makefile; then
     printf "You must run this script from within port directory.\n"
     exit 1
@@ -21,8 +57,6 @@ if [ $# = 1 ]; then
 else
     old_portname=$portname
 fi
-#printf "port name = $portname\n"
-#printf "category = $category\n"
 
 if [ ! -e /usr/ports/$category/$old_portname ]; then
     printf "Error: /usr/ports/$category/$old_portname does not exist.\n"
diff --git a/Scripts/port-mkpatch b/Scripts/port-mkpatch
--- a/Scripts/port-mkpatch
+++ b/Scripts/port-mkpatch
@@ -1,6 +1,50 @@
 #!/bin/sh -e
 
 ##########################################################################
+#   Synopsis:
+#       port-mkpatch work/path/to/file
+#       
+#   Description:
+#       .B port-mkpatch
+#       Generates a proper FreeBSD ports patch in portname/files
+#       by diffing work/path/to/file.orig and work/path/to/file.
+#       It should not be necessary to run "make makepatch" to
+#       fomat the patch file generated by port-mkpatch.  It should
+#       already be compatible.
+#
+#       .B port-mkpatch
+#       is not usually run directly, but via port-patch-edit(1).
+#       
+#   Arguments:
+#       work/path/to/file   Path to patched file relative to port directory
+#       
+#   Returns:
+#       0 on success, non-zero error codes otherwise
+#
+#   Examples:
+#       port-mkpatch work/fasda-0.2.0/fold-change.c
+#
+#   See also:
+#       port-check(1), port-create(1), port-diff(1), port-patch-edit(1),
+#       port-remake(1), port-reinstall(1), port-restage(1)
+##########################################################################
+
+usage()
+{
+    printf "Usage: $0\n"
+    exit 64     # sysexits(3) EX_USAGE
+}
+
+
+##########################################################################
+#   Main
+##########################################################################
+
+if [ $# != 0 ]; then
+    usage
+fi
+
+##########################################################################
 #   Script description:
 #       Generate a patch file and store in files dir with canonical name
 #       
diff --git a/Scripts/port-restage b/Scripts/port-restage
--- a/Scripts/port-restage
+++ b/Scripts/port-restage
@@ -1,5 +1,42 @@
 #!/bin/sh -e
 
+##########################################################################
+#   Synopsis:
+#       port-restage
+#       
+#   Description:
+#       .B port-restage
+#       reruns the stage and install phases of the port in the current
+#       working directory, without running any prior stages such as
+#       fetch, patch, build, etc.  It is meant for quickly testing fixes to
+#       the stage and install targets or pkg-plist.
+#       
+#   Arguments:
+#       None
+#       
+#   Returns:
+#       0 on success, non-zero error codes otherwise
+#
+#   See also:
+#       port-check(1), port-create(1), port-diff(1), port-mkpatch(1),
+#       port-patch-edit(1), port-reinstall(1), port-remake(1)
+##########################################################################
+
+usage()
+{
+    printf "Usage: $0\n"
+    exit 64     # sysexits(3) EX_USAGE
+}
+
+
+##########################################################################
+#   Main
+##########################################################################
+
+if [ $# != 0 ]; then
+    usage
+fi
+
 rm -rf work/.build_done* work/.stage_done* work/.PLIST.mktmp work/stage
 make deinstall reinstall
 
